[package]
name = "rust-gtk-counter"
version = "0.1.0"
authors = ["Kyle Galloway <kyle.galloway.1993@gmail.com>"]
edition = "2018"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]

